image: node:12

stages:
    - dependencias
    - build
    - containerization
    - deploy
    
cache:
    paths:
        - node_modules/

install_dependencies:
    stage: dependencias
    script:
        - npm install
        - npm install typescript
    artifacts:
        paths:
            - node_modules/

transpilacion:
    stage: build
    script:
        - npm run build

containerization:
    stage: containerization # must match the stage name declared above
    script:
        # Build the container image
        #- npm run build
        - docker build -t n_almacenes .
        # Push the container image to the registry
        #- docker push my-registry/my-application
        # Cleanup by removing the local image
        #- docker image rm my-registry/my-application

deploy_to_desarrollo:
    stage: deploy
    script: 
        - docker-compose down 
        - docker-compose up -d 
    only:
        - desarrollo

#deploy_to_qas:
#    stage: deploy
#    script: 
#        - docker-compose down 
#        - docker-compose up -d 
#    only:
#        - qas
#
#deploy_to_prod:
#    stage: deploy
#    script: 
#        - docker-compose down 
#        - docker-compose up -d 
#    only:
#        - master
#    when: manual
