version: "2"

services:

    node-almacenes:
        #image: n_almacenes:latest
        build: 
            context: .
            args: 
                - config=transven
        container_name: node_almacenes
        restart: always
        ports:  
            #El puerto expuesto en el caso de node debe ser el mismo por el que corre la app 
            - "3004:3004"
        #volumes: 
            #- ./app:/app
        environment:
            - PORT=3004
            - SECRET_KEY=hola_yo
        
        working_dir: /app
        command: bash -c "npm install && npm start"
        networks:
            - webnet            


networks:
    webnet: 
