version: "2"

services:

    node-almacenes:
        image: thk/docker-test:latest
        #build: 
        #    context: .
        #    args: 
        #        - config=transven
        container_name: node_almacenes
        restart: always
        ports:  
            #El puerto expuesto en el caso de node debe ser el mismo por el que corre la app 
            - "3004:3004"
        #volumes: 
            #- ./app:/app
        environment:
            - MYSQL_SERVER=10.10.0.7
            - MYSQL_PORT=3306
            - MYSQL_DB=intranet
            - MYSQL_USER=root
            - MYSQL_PW=.4C3r04dm1n
            # si se necesita trabajar con la base de datos local solo cambiar el valor de la variable DEPLOYMENT, no borrarla
            - DEPLOYMENT=dev
            - PORT=3004
            - SECRET_KEY=hola_yo
        
        working_dir: /app
        command: bash -c "npm install && npm start"
        networks:
            - webnet            


networks:
    webnet: 
