version: "2"

services:

    node-almacenes:
        #image: n_almacenes:latest
        build: 
            context: .
            args: 
                - config=transven
        container_name: node_almacenes
        restart: always
        ports:  
            #El puerto expuesto en el caso de node debe ser el mismo por el que corre la app 
            - "3004:3004"
        #volumes: 
            #- ./app:/app
        environment:
            - MYSQL_SERVER=$MYSQL_SERVER
            - MYSQL_PORT=$MYSQL_PORT
            - MYSQL_DB=$MYSQL_DB
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PW=$MYSQL_PW
            # si se necesita trabajar con la base de datos local solo cambiar el valor de la variable DEPLOYMENT, no borrarla
            - DEPLOYMENT=dev
            - PORT=3004
            - SECRET_KEY=hola_yo
        
        working_dir: /app
        command: bash -c "npm install && npm start"
        networks:
            - webnet            


networks:
    webnet: 
